### ISSUE TITLE
我想问一下，能不能在ubuntu的纯命令终端下运行？

### ISSUE THREAD

**Issue by jzp820927** [yinghuocho/firefly-proxy#9]
如题？

**Comment by yinghuocho** [comment]
可以，直接下载源代码运行 proxyonly.py，没有界面，不会启动浏览器．需要手动设置代理．代理地址参考 config.json 中的如下项（作用直观理解配置项名称）   

http_proxy_ip
http_proxy_port
socks_proxy_ip
socks_proxy_port
enable_http_proxy
enable_socks_proxy

欢迎反馈效果和问题，谢谢！

**Comment by jzp820927** [comment]
root@ubuntu:~/firefly-proxy# python proxyonly.py
Traceback (most recent call last):
  File "proxyonly.py", line 18, in <module>
    from lib.utils import init_logging, local_update_datafile, set_ca_certs_env, singleton_check, singleton_clean
  File "/root/firefly-proxy/lib/utils.py", line 13, in <module>
    import requesocks
ImportError: No module named requesocks

运行后，提示如上错误信息，看提示好像是说没有 requesocks 这个模块？不知道是缺少什么依赖包？还是其他什么问题？

**Comment by yinghuocho** [comment]
缺少 requesocks 模块

pip install requesocks 安装一下pip install requesocks

**Comment by jzp820927** [comment]
root@ubuntu:~/firefly-proxy# python proxyonly.py
'module' object has no attribute 'sslwrap'
'module' object has no attribute 'sslwrap'
meek relay (https://ajax.aspnetcdn.com/,az672578.vo.msecnd.net) is not valid
'module' object has no attribute 'sslwrap'
'module' object has no attribute 'sslwrap'
meek relay (https://a0.awsstatic.com/,dswpv736infni.cloudfront.net) is not valid
Not supported proxy scheme socks5 give it another chance ...
Not supported proxy scheme socks5 give it another chance ...
failed to update meek relays: Not supported proxy scheme socks5
Not supported proxy scheme socks5 give it another chance ...
Not supported proxy scheme socks5 give it another chance ...
failed to update blacklist: Not supported proxy scheme socks5
Not supported proxy scheme socks5 give it another chance ...
Not supported proxy scheme socks5 give it another chance ...
failed to update hosts: Not supported proxy scheme socks5
[2015-05-25 21:52:27,489][gsocks.server][ERROR] - [Exception][SocksServer]: list index out of range
[2015-05-25 21:52:27,489][gsocks.server][ERROR] - [Exception][SocksServer]: list index out of range
[2015-05-25 21:52:27,490][gsocks.relay][ERROR] - [Exception][RelaySession]:
[2015-05-25 21:52:27,490][gsocks.relay][ERROR] - [Exception][RelaySession]:
[2015-05-25 21:52:29,363][gsocks.relay][INFO] - TCP request address: (www.whatismyip.com:80)
[2015-05-25 21:52:29,363][gsocks.relay][INFO] - TCP request address: (www.whatismyip.com:80)
[2015-05-25 21:52:30,082][gsocks.relay][INFO] - TCP request address: (tpc.googlesyndication.com:443)
[2015-05-25 21:52:30,082][gsocks.relay][INFO] - TCP request address: (tpc.googlesyndication.com:443)
[2015-05-25 21:52:30,097][gsocks.relay][INFO] - TCP request address: (securepubads.g.doubleclick.net:4      43)
[2015-05-25 21:52:30,097][gsocks.relay][INFO] - TCP request address: (securepubads.g.doubleclick.net:4      43)
[2015-05-25 21:52:30,106][gsocks.relay][INFO] - TCP request address: (securepubads.g.doubleclick.net:4      43)
[2015-05-25 21:52:30,106][gsocks.relay][INFO] - TCP request address: (securepubads.g.doubleclick.net:4      43)
[2015-05-25 21:52:30,113][gsocks.relay][INFO] - TCP request address: (securepubads.g.doubleclick.net:4      43)
[2015-05-25 21:52:30,113][gsocks.relay][INFO] - TCP request address: (securepubads.g.doubleclick.net:4      43)
[2015-05-25 21:52:30,128][gsocks.relay][INFO] - TCP request address: (ajax.cloudflare.com:443)
[2015-05-25 21:52:30,128][gsocks.relay][INFO] - TCP request address: (ajax.cloudflare.com:443)
[2015-05-25 21:52:30,134][gsocks.relay][INFO] - TCP request address: (fonts.googleapis.com:443)
[2015-05-25 21:52:30,134][gsocks.relay][INFO] - TCP request address: (fonts.googleapis.com:443)
[2015-05-25 21:52:30,149][gsocks.relay][INFO] - TCP request address: (www.whatismyip.com:443)
[2015-05-25 21:52:30,149][gsocks.relay][INFO] - TCP request address: (www.whatismyip.com:443)
[2015-05-25 21:52:30,153][gsocks.relay][INFO] - TCP request address: (www.googletagservices.com:443)
[2015-05-25 21:52:30,153][gsocks.relay][INFO] - TCP request address: (www.googletagservices.com:443)

[2015-05-25 21:52:34,565][gsocks.relay][ERROR] - [Exception][RelaySession]:
[2015-05-25 21:52:34,565][gsocks.relay][ERROR] - [Exception][RelaySession]:
[2015-05-25 21:52:34,604][gsocks.relay][INFO] - TCP request address: (stats.g.doubleclick.net:443)
[2015-05-25 21:52:34,604][gsocks.relay][INFO] - TCP request address: (stats.g.doubleclick.net:443)
[2015-05-25 21:52:34,621][gsocks.server][ERROR] - [Exception][SocksServer]: list index out of range
[2015-05-25 21:52:34,621][gsocks.server][ERROR] - [Exception][SocksServer]: list index out of range
[2015-05-25 21:52:34,622][gsocks.relay][ERROR] - [Exception][RelaySession]:
[2015-05-25 21:52:34,622][gsocks.relay][ERROR] - [Exception][RelaySession]:
[2015-05-25 21:52:34,632][gsocks.relay][INFO] - TCP request address: (fbstatic-a.akamaihd.net:443)
[2015-05-25 21:52:34,632][gsocks.relay][INFO] - TCP request address: (fbstatic-a.akamaihd.net:443)

[2015-05-25 21:52:52,045][gsocks.relay][ERROR] - [Exception][RelaySession]: [Errno 104] Connection res      et by peer
[2015-05-25 21:52:52,045][gsocks.relay][ERROR] - [Exception][RelaySession]: [Errno 104] Connection res      et by peer

[2015-05-25 21:53:30,856][gsocks.relay][INFO] - TCP request address: (www.gstatic.com:80)
[2015-05-25 21:53:30,856][gsocks.relay][INFO] - TCP request address: (www.gstatic.com:80)
[2015-05-25 21:53:30,919][gsocks.server][ERROR] - [Exception][SocksServer]: list index out of range
[2015-05-25 21:53:30,919][gsocks.server][ERROR] - [Exception][SocksServer]: list index out of range
[2015-05-25 21:53:30,921][gsocks.relay][ERROR] - [Exception][RelaySession]:
[2015-05-25 21:53:30,921][gsocks.relay][ERROR] - [Exception][RelaySession]:

**Comment by jzp820927** [comment]
[2015-05-25 21:52:27,489][gsocks.server][ERROR] - [Exception][SocksServer]: list index out of range
[2015-05-25 21:52:27,490][gsocks.relay][ERROR] - [Exception][RelaySession]:

**Comment by yinghuocho** [comment]
应该是 python 版本和 gevent 的 ssl 之间的兼容性问题，导致两个 meek 代理都不能连接．

**Comment by yinghuocho** [comment]
sudo pip install gevent --upgrade

升级 gevent 到最新版应该可以解决．

**Comment by jzp820927** [comment]
root@ubuntu:~/firefly-proxy# pip install gevent --upgrade
Requirement already up-to-date: gevent in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: greenlet>=0.4.7 in /usr/local/lib/python2.7/dist-packages (from gevent)
Cleaning up...

运行后，是这个提示，是不是已经是最新版了？再次运行萤火虫代理，还是和上面一样的错误信息...
----------------------------------------------------------------------------------------
另外附上我的系统信息，和 python 版本
安装的 Ubuntu 服务器版本，无 X 环境。
Ubuntu Server 14.10 (GNU/Linux 3.16.0-23-generic x86_64)

root@ubuntu:~/firefly-proxy# python --version
Python 2.7.8

**Comment by yinghuocho** [comment]
python 2.7.9 gevent 1.0.2 Ubuntu 14.04 是可以运行的

查看 gevent 版本 
$python
>import gevent
>gevent.__version__

**Comment by jzp820927** [comment]
反馈一下，Ubuntu 还是没成功运行，但是我在最新版的 Fedora 22，也就是 2015-05-26 刚出来的最新版上 完美成功运行，代理使用也正常， Fedora 22 上的软件版本是 python 2.7.9，gevent 1.0.2，这个我可以确定，但是 Ubuntu 上不知道是什么原因，也不知道怎么看 gevent 的版本，Python 是 2.7.8。

还有一个问题，我在  Fedora 22 上改 config.json 中的监听地址，把，127.0.0.1，改成 0.0.0.0，运行以后，netstat 查看，确实监听的 0.0.0.0，但是局域网其他机子无法使用本机代理，不知道 Fedora 22 是不是有网络权限问题，还是其他什么问题？希望作者帮忙看看是什么问题？

**Comment by yinghuocho** [comment]
开启 socks 代理出错是一个 bug，已经修正了．谢谢！

**Comment by jzp820927** [comment]
感谢作者及时更新，我再试试看行不行。
